import 'dotenv/config';
import fs from 'fs';
import path from 'path';

/**
 * This file gets the current NPS activity names and ids and updates our npsActivities.js file with the up to date information.
 */
const NPS_API_KEY = process.env.NEXT_PUBLIC_NPS_API_KEY;
const OUT_FILE = path.resolve('src/constants/npsActivities.js');

async function fetchActivityList() {
  const res = await fetch(`https://developer.nps.gov/api/v1/activities?api_key=${NPS_API_KEY}`);
  const { data } = await res.json();

  return data.map(({ id, name }) => ({ id, name }));
}

function generateFileContent(activityList) {
  const listStr = JSON.stringify(activityList, null, 2);

  const nameToId = activityList
    .map(({ id, name }) => `  "${name.toLowerCase()}": "${id}"`)
    .join(',\n');

  const idToName = activityList
    .map(({ id, name }) => `  "${id}": "${name}"`)
    .join(',\n');

  return `
// AUTO-GENERATED BY scripts/updateNpsActivities.js

export const NPS_ACTIVITY_LIST = ${listStr};

export const NPS_ACTIVITY_NAME_TO_ID = {
${nameToId}
};

export const NPS_ACTIVITY_ID_TO_NAME = {
${idToName}
};
`;
}

async function main() {
  const activities = await fetchActivityList();
  const fileContent = generateFileContent(activities);

  fs.writeFileSync(OUT_FILE, fileContent);
  console.log(`✅ NPS activity constants updated at: ${OUT_FILE}`);
}

main().catch(err => {
  console.error('❌ Failed to update activity list:', err);
  process.exit(1);
});
